$(document).ready(function(){
    $("#1").click(function(){
      $(this).html("0");
    });
    $("#2").click(function(){
      $(this).html("0");
    });
    $("#3").click(function(){
      $(this).html("0");
    });
    $("#4").click(function(){
      $(this).html("0");
    });
    $("#5").click(function(){
      $(this).html("0");
    });
    $("#6").click(function(){
      $(this).html("0");
    });
    $("#7").click(function(){
      $(this).html("0");
    });
    $("#8").click(function(){
      $(this).html("0");
    });
    
  });